#!/usr/bin/env bash

set -euo pipefail

readonly REQUIRED_KEY_CONTENT='agent_api_key_test'

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

is_integer_in_range() {
  local value="$1"
  local minimum="$2"
  local maximum="$3"

  [[ "$value" =~ ^[0-9]+$ ]] && ((value >= minimum && value <= maximum))
}

port_is_available() {
  command -v ss >/dev/null 2>&1 || fail "'ss' 명령을 찾을 수 없습니다. iproute2를 설치한 뒤 다시 실행하세요."
  ! ss -H -ltn | awk '{print $4}' | grep -Eq '(^|:|\])15034$'
}

install_binary() {
  local archive_path="$1"
  local binary_name="$2"

  command -v unzip >/dev/null 2>&1 || fail "'unzip' 명령을 찾을 수 없습니다. unzip을 설치한 뒤 다시 실행하세요."
  unzip -Z1 "$archive_path" | grep -Fxq "$binary_name" || fail "ZIP에 필요한 바이너리가 없습니다: $binary_name"
  unzip -p "$archive_path" "$binary_name" >"$AGENT_BINARY"
  chmod 0755 "$AGENT_BINARY"
}

write_environment_file() {
  local output_path="$1"

  {
    printf '# Generated by scripts/prepare_environment.sh\n'
    printf 'export AGENT_HOME=%q\n' "$AGENT_HOME"
    printf 'export AGENT_PORT=%q\n' "$AGENT_PORT"
    printf 'export AGENT_UPLOAD_DIR=%q\n' "$AGENT_UPLOAD_DIR"
    printf 'export AGENT_KEY_PATH=%q\n' "$AGENT_KEY_PATH"
    printf 'export AGENT_LOG_DIR=%q\n' "$AGENT_LOG_DIR"
    printf 'export MEMORY_LIMIT=%q\n' "$MEMORY_LIMIT"
    printf 'export CPU_MAX_OCCUPY=%q\n' "$CPU_MAX_OCCUPY"
    printf 'export MULTI_THREAD_ENABLE=%q\n' "$MULTI_THREAD_ENABLE"
    printf 'export AGENT_BINARY=%q\n' "$AGENT_BINARY"
  } >"$output_path"

  chmod 0600 "$output_path"
}

verify_environment() {
  [[ "$(id -u)" -ne 0 ]] || fail 'root 계정으로 실행할 수 없습니다.'
  [[ "$AGENT_PORT" == '15034' ]] || fail 'AGENT_PORT는 15034여야 합니다.'
  [[ -d "$AGENT_UPLOAD_DIR" ]] || fail "업로드 디렉터리가 없습니다: $AGENT_UPLOAD_DIR"
  [[ -d "$AGENT_KEY_PATH" ]] || fail "API key 디렉터리가 없습니다: $AGENT_KEY_PATH"
  [[ -d "$AGENT_LOG_DIR" && -w "$AGENT_LOG_DIR" ]] || fail "로그 디렉터리에 쓸 수 없습니다: $AGENT_LOG_DIR"
  [[ -x "$AGENT_BINARY" ]] || fail "선택된 바이너리를 실행할 수 없습니다: $AGENT_BINARY"
  [[ -f "$AGENT_KEY_PATH/secret.key" ]] || fail 'secret.key 파일이 없습니다.'
  [[ "$(<"$AGENT_KEY_PATH/secret.key")" == "$REQUIRED_KEY_CONTENT" ]] || fail 'secret.key 내용이 올바르지 않습니다.'
  is_integer_in_range "$MEMORY_LIMIT" 50 512 || fail 'MEMORY_LIMIT는 50~512 사이의 정수여야 합니다.'
  is_integer_in_range "$CPU_MAX_OCCUPY" 10 100 || fail 'CPU_MAX_OCCUPY는 10~100 사이의 정수여야 합니다.'

  case "$MULTI_THREAD_ENABLE" in
    true | false | 1 | 0 | yes | no) ;;
    *) fail 'MULTI_THREAD_ENABLE은 true/false, 1/0, yes/no 중 하나여야 합니다.' ;;
  esac

  port_is_available || fail '0.0.0.0:15034 포트가 이미 사용 중입니다.'
}

main() {
  [[ "$(uname -s)" == 'Linux' ]] || fail '이 스크립트는 Linux 환경에서만 실행할 수 있습니다.'
  [[ "$(id -u)" -ne 0 ]] || fail 'root가 아닌 일반 사용자 계정으로 실행하세요.'

  local script_dir
  local project_dir
  local binary_name
  local archive_path

  script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
  project_dir="$(cd -- "$script_dir/.." && pwd)"
  archive_path="$project_dir/agent-app-leak.zip"

  case "$(uname -m)" in
    x86_64 | amd64) binary_name='agent-leak-app-x86' ;;
    aarch64 | arm64) binary_name='agent-leak-app-arm64' ;;
    *) fail "지원하지 않는 CPU 아키텍처입니다: $(uname -m)" ;;
  esac

  readonly AGENT_HOME="${AGENT_HOME:-$HOME/agent-leak-lab}"
  [[ "$AGENT_HOME" == /* ]] || fail 'AGENT_HOME은 절대 경로여야 합니다.'

  readonly AGENT_PORT="${AGENT_PORT:-15034}"
  readonly AGENT_UPLOAD_DIR="${AGENT_UPLOAD_DIR:-$AGENT_HOME/upload_files}"
  readonly AGENT_KEY_PATH="${AGENT_KEY_PATH:-$AGENT_HOME/api_keys}"
  readonly AGENT_LOG_DIR="${AGENT_LOG_DIR:-$AGENT_HOME/logs}"
  readonly MEMORY_LIMIT="${MEMORY_LIMIT:-256}"
  readonly CPU_MAX_OCCUPY="${CPU_MAX_OCCUPY:-80}"
  readonly MULTI_THREAD_ENABLE="${MULTI_THREAD_ENABLE:-true}"
  readonly AGENT_BINARY="$AGENT_HOME/bin/agent-leak-app"

  [[ -f "$archive_path" ]] || fail "제공 파일을 찾을 수 없습니다: $archive_path"

  mkdir -p "$AGENT_UPLOAD_DIR" "$AGENT_KEY_PATH" "$AGENT_LOG_DIR" "$AGENT_HOME/bin"
  install_binary "$archive_path" "$binary_name"
  printf '%s\n' "$REQUIRED_KEY_CONTENT" >"$AGENT_KEY_PATH/secret.key"
  chmod 0600 "$AGENT_KEY_PATH/secret.key"

  verify_environment
  write_environment_file "$AGENT_HOME/agent.env"

  printf '\n환경 준비와 검증이 완료되었습니다.\n'
  printf '선택된 아키텍처: %s\n' "$(uname -m)"
  printf '선택된 바이너리: %s\n' "$binary_name"
  printf 'AGENT_HOME: %s\n' "$AGENT_HOME"
  printf '환경변수 적용 명령: source %q\n' "$AGENT_HOME/agent.env"
  printf '다음 단계에서 사용할 실행 파일: %s\n' "$AGENT_BINARY"
}

main "$@"
